name: Awesome Bot

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
      with:
        egress-policy: audit

    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - uses: ruby/setup-ruby@0dafeac902942906541bc140009cdbf32665b601 # v1.315.0
      with:
        ruby-version: '2.7'
        
    - name: Install Awesome Bot
      run: gem install awesome_bot
      
    - name: Verify links
      run: awesome_bot README.md --skip-save-results --allow-redirect -a 429 -w raw.githubusercontent.com
